version: '3.9'

services:
  server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'monke'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: